mysite_news/mysite_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

mysite_news/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:year>/', views.year_archive, name='year'),
    path('<headline>/', views.article_detail, name='headline'),
]

mysite_news/news/models.py
from django.db import models

class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):              # __unicode__ on Python 2
        return self.full_name

class Article(models.Model):
    pub_date = models.DateField()
    headline = models.CharField(max_length=200)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

mysite_news/news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Article

def index(request):
    article_list = Article.objects.order_by('-pub_date')[:5]
    year_list = []
    for i in article_list:
        year_list.append(i.pub_date.year)
    year_list = list(set(year_list))
    context = {'year_list': year_list}
    return render(request, 'news/base.html', context)

def year_archive(request, year):
    a_list = Article.objects.filter(pub_date__year=year)
    context = {'year': year, 'article_list': a_list}
    return render(request, 'news/year_archive.html', context)

def article_detail(request, headline):
    art = get_object_or_404(Article, headline=headline)
    return render(request, 'news/detail.html', {'article':art,})

mysite_news/news/templates/news/base.html
{% if year_list %}
    <ul>
    {% for year in year_list %}
        <li><a href="{% url 'news:year' year %}">{{ year }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No articles are available.</p>
{% endif %}

mysite_news/news/templates/news/detail.html
{% block content %}
<h1>{{ article.headline }}</h1>
    <p>{{ article.content }}</a></p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:"F j, Y" }}</p>
{% endblock %}

mysite_news/news/templates/news/year_archive.html
{% block content %}
<h1>Articles for {{ year }}</h1>

{% for article in article_list %}
<div style="background-color: beige;">
    <a href="{% url 'news:headline' article.headline %}">{{ article.headline }}</a></p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:"F j, Y" }}</p></div>
{% endfor %}
{% endblock %}